-- ============================================================
-- VIDYASETU — SEED: MCQ QUESTION BANK
-- Migration: 002_seed_mcq_questions.sql
-- Seeds all questions from 13_skill_verify.html into DB.
-- Correct answers stored server-side only — never sent to client raw.
-- ============================================================

INSERT INTO public.mcq_questions (skill_name, question, option_a, option_b, option_c, option_d, correct, difficulty) VALUES

-- ─── REACT (10 questions) ────────────────────────────────────
('react', 'What hook is used to manage state in a functional React component?',
  'useEffect', 'useState', 'useRef', 'useMemo', 1, 1),
('react', 'What does the dependency array in useEffect control?',
  'Component styling', 'When the effect re-runs', 'The return value', 'Component mounting', 1, 1),
('react', 'Which of the following is NOT a valid React hook?',
  'useReducer', 'useCallback', 'useHistory', 'useContext', 2, 2),
('react', 'How do you pass data from a parent to a child component?',
  'State', 'Context', 'Props', 'Refs', 2, 1),
('react', 'What does React.memo() do?',
  'Memoizes a function', 'Prevents unnecessary re-renders', 'Creates a memo pad UI', 'Stores data in memory', 1, 2),
('react', 'What is the virtual DOM?',
  'A browser API', 'A lightweight JS representation of the real DOM', 'A CSS framework', 'A database layer', 1, 1),
('react', 'Which lifecycle method is equivalent to useEffect with an empty dependency array?',
  'componentDidUpdate', 'componentWillMount', 'componentDidMount', 'shouldComponentUpdate', 2, 2),
('react', 'What is JSX?',
  'A JavaScript library', 'A syntax extension for JavaScript', 'A CSS preprocessor', 'A build tool', 1, 1),
('react', 'How do you handle forms in React?',
  'Only uncontrolled components', 'Only controlled components', 'Both controlled and uncontrolled', 'Neither', 2, 2),
('react', 'What is the purpose of the key prop in lists?',
  'Styling elements', 'Helping React identify which items changed', 'Sorting the list', 'Adding event handlers', 1, 1),

-- ─── PYTHON (10 questions) ───────────────────────────────────
('python', 'What is the output of `print(type([]))`?',
  '<class ''list''>', '<class ''tuple''>', '<class ''dict''>', '<class ''set''>', 0, 1),
('python', 'Which keyword is used to define a function in Python?',
  'function', 'func', 'def', 'define', 2, 1),
('python', 'What does `len("Hello")` return?',
  '4', '5', '6', 'Error', 1, 1),
('python', 'Which of these is a mutable data type in Python?',
  'str', 'tuple', 'int', 'list', 3, 1),
('python', 'What is a decorator in Python?',
  'A design pattern for UI', 'A function that modifies another function', 'A type of variable', 'A loop construct', 1, 2),
('python', 'What does `//` operator do in Python?',
  'Regular division', 'Floor division', 'Modulo', 'Exponentiation', 1, 1),
('python', 'Which method adds an element to the end of a list?',
  'insert()', 'add()', 'append()', 'push()', 2, 1),
('python', 'What is a lambda function?',
  'A named function', 'An anonymous function', 'A recursive function', 'A generator function', 1, 2),
('python', 'What does PEP 8 refer to?',
  'Python Enhancement Proposal for style guide', 'A Python package', 'A debugging tool', 'A testing framework', 0, 2),
('python', 'What is the output of `bool("")`?',
  'True', 'False', 'None', 'Error', 1, 1),

-- ─── FIGMA (10 questions) ────────────────────────────────────
('figma', 'What is Auto Layout in Figma?',
  'Automatic color selection', 'A feature to create responsive designs with dynamic spacing', 'A plugin for icons', 'Animation tool', 1, 1),
('figma', 'What are Components in Figma?',
  'Color palettes', 'Reusable design elements with instances', 'File types', 'Export formats', 1, 1),
('figma', 'Which shortcut creates a frame in Figma?',
  'R', 'F', 'A', 'C', 1, 1),
('figma', 'What is a Design Token?',
  'A payment method', 'A reusable value like color, spacing, or typography', 'A file format', 'A collaboration feature', 1, 2),
('figma', 'What does "Detach Instance" do?',
  'Deletes the component', 'Breaks the link between an instance and its main component', 'Removes all styles', 'Exports the design', 1, 2),
('figma', 'What is the difference between Fill and Stroke?',
  'Fill is for text, Stroke is for shapes', 'Fill colors the inside, Stroke outlines the edge', 'They are the same thing', 'Fill is for images only', 1, 1),
('figma', 'What are Variants in Figma?',
  'Different file versions', 'Different states of a component grouped together', 'Color themes', 'Animation keyframes', 1, 2),
('figma', 'What is a Style in Figma?',
  'A CSS file', 'A reusable set of properties like color or text style', 'A plugin', 'An export setting', 1, 1),
('figma', 'What does Boolean Operations do?',
  'Adds logic to prototypes', 'Combines or subtracts shapes', 'Creates animations', 'Manages layers', 1, 2),
('figma', 'What file format does Figma use natively?',
  '.fig', '.sketch', '.psd', '.ai', 0, 1),

-- ─── JAVASCRIPT (10 questions) ───────────────────────────────
('javascript', 'What does `===` do in JavaScript?',
  'Assignment', 'Loose equality', 'Strict equality', 'Not equal', 2, 1),
('javascript', 'What is a closure in JavaScript?',
  'A CSS property', 'A function with access to its outer scope variables', 'A loop type', 'A data structure', 1, 2),
('javascript', 'What does `Array.prototype.map()` return?',
  'undefined', 'The original array', 'A new array with transformed elements', 'A boolean', 2, 1),
('javascript', 'What is event bubbling?',
  'An animation technique', 'Events propagating from child to parent elements', 'A memory leak', 'Error handling', 1, 2),
('javascript', 'Which keyword declares a block-scoped variable?',
  'var', 'let', 'function', 'global', 1, 1),
('javascript', 'What does `Promise.all()` do?',
  'Runs promises sequentially', 'Resolves when all promises resolve', 'Cancels all promises', 'Creates a new promise', 1, 2),
('javascript', 'What is the `this` keyword?',
  'Always refers to the global object', 'Refers to the current execution context', 'A reserved variable name', 'Refers to the parent element', 1, 2),
('javascript', 'What does JSON.parse() do?',
  'Converts JSON string to JS object', 'Converts JS object to JSON string', 'Validates JSON', 'Formats JSON', 0, 1),
('javascript', 'What is destructuring?',
  'Deleting objects', 'Extracting values from arrays/objects into variables', 'Memory cleanup', 'Error handling', 1, 1),
('javascript', 'What is the output of `typeof null`?',
  '"null"', '"undefined"', '"object"', '"boolean"', 2, 2),

-- ─── MACHINE LEARNING (10 questions) ────────────────────────
('ml', 'What is supervised learning?',
  'Learning without any data', 'Learning from labeled data', 'Learning from rewards', 'Unsupervised clustering', 1, 1),
('ml', 'What does overfitting mean?',
  'Model performs well on training data but poorly on new data', 'Model is too simple', 'Model trains too slowly', 'Model uses too little data', 0, 2),
('ml', 'What is a neural network activation function?',
  'A function that starts training', 'A function that introduces non-linearity', 'A loss function', 'A data preprocessing step', 1, 2),
('ml', 'What is the purpose of a validation set?',
  'Training the model', 'Tuning hyperparameters and preventing overfitting', 'Testing final performance', 'Storing data', 1, 2),
('ml', 'What does gradient descent do?',
  'Increases the loss', 'Finds the minimum of a cost function', 'Generates data', 'Normalizes features', 1, 2),
('ml', 'What is a confusion matrix?',
  'A data cleaning tool', 'A table showing prediction results vs actual values', 'A neural network layer', 'A feature selection method', 1, 2),
('ml', 'Which is NOT a type of machine learning?',
  'Supervised', 'Unsupervised', 'Reinforced', 'Compiled', 3, 1),
('ml', 'What is feature engineering?',
  'Building hardware', 'Creating/transforming input variables to improve model performance', 'Writing documentation', 'Database design', 1, 2),
('ml', 'What does regularization prevent?',
  'Underfitting', 'Overfitting', 'Data loss', 'Slow training', 1, 2),
('ml', 'What is cross-validation?',
  'Validating data types', 'A technique to assess model generalization using data splits', 'Crossing out bad data', 'Double-checking labels', 1, 2);
